### ISSUE TITLE
Reward id for '20+ submissions'  inside a hook is not translated from GeDIL id to GS id

### ISSUE THREAD

**Issue by hvsio** [FGPE-Erasmus/gamification-service#21]
+20 submission reward - I could not map the place where the issue originates from, console.logs inside hooks `importGedIl` were printing the translated from gedil to GS id but in the GS hooks repo, it was still the gedil id and resulted in errors during reward assignment

**Comment by josepaiva94** [comment]
Please check https://github.com/FGPE-Erasmus/gamification-service/blob/master/src/hook/hook.service.ts#L79 
I've passed actions exactly as they come in the GEdIL package, but its parameters may need to be mapped. Can you fix?

**Comment by hvsio** [comment]
solved by removing  **if (trigger.parameters[0] && trigger.parameters[0] !== null)** in  `executeHook()` in `hook.service.ts`
